# This is a basic workflow to help you get started with Actions

name: Araba Build and Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cat * >> butun_meyveler.txt
      - name: Butun Meyveleri Tek bir dosyada topladık
        uses: actions/upload-artifact@v2
        with: 
          name: Butun Meyveler Artifact
          path: butun_meyveler.txt

  test:
    needs: build
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Butun Meyveleri build den download ediyoruz
        uses: actions/download-artifact@v2
        with: 
          name: Butun Meyveler Artifact
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          grep "Elma" butun_meyveler.txt
          grep "Armut" butun_meyveler.txt
          grep "Portakal" butun_meyveler.txt
